// front/styles/styles.js
import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

// Responsive font boyutları için yardımcı fonksiyon
const calcFontSize = (size) => {
  return `clamp(${size * 0.8}px, ${size * 0.15}vw, ${size * 1.2}px)`;
};

// Responsive boyutlar için yardımcı fonksiyon
const calcSize = (size) => {
  return `clamp(${size * 0.8}px, ${size * 0.1}vw, ${size * 1.2}px)`;
};

// Ortak yazı stilleri
const textStyles = {
  primary: {
    color: '#fff',
    letterSpacing: calcSize(1),
    textShadow: `0 ${calcSize(2)} ${calcSize(4)} rgba(0,0,0,0.2)`,
  }
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1f25',
    minHeight: '100vh',
    width: '98%',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    overflowY: 'auto',
    zIndex: 1,
    margin: calcSize(16),
    scrollBehavior: 'smooth',
    scrollSnapType: 'y mandatory',
    '&::-webkit-scrollbar': {
      width: '8px',
    },
    '&::-webkit-scrollbar-track': {
      background: 'rgba(255, 255, 255, 0.1)',
    },
    '&::-webkit-scrollbar-thumb': {
      background: 'rgba(255, 255, 255, 0.2)',
      borderRadius: '4px',
    },
  },
  scrollViewContent: {
    flex: 1,
    backgroundColor: '#1a1f25',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    margin: 0,
    maxWidth: '1800px',
    scrollSnapAlign: 'start',
    '@media (max-width: 768px)': {
      scrollSnapStop: 'always',
    },
  },
  heroTitle: {
    ...textStyles.primary,
    fontSize: calcFontSize(42),
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: '1vh',
    marginTop: '2vh',
  },
  heroSubtitle: {
    ...textStyles.primary,
    fontSize: calcFontSize(18),
    textAlign: 'center',
    opacity: 0.9,
    marginBottom: '2vh',
  },
  mainButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '2vw',
    padding: '16px',
    transition: 'all 0.3s ease',
    minHeight: '200px',
    height: 'auto',
    maxHeight: '40vh',
    flexWrap: 'wrap'
  },
  mainButtonsContainerSmall: {
    minHeight: '80px',
    height: 'auto',
    marginTop: '1vh',
    marginBottom: '1vh',
  },
  mainButton: {
    width: '45%',
    maxWidth: calcSize(400),
    minHeight: '180px',
    height: 'auto',
    maxHeight: '35vh',
    backgroundColor: '#007bff',
    borderRadius: calcSize(25),
    justifyContent: 'center',
    alignItems: 'center',
    transition: 'all 0.3s ease',
    cursor: 'pointer',
    boxShadow: `0 ${calcSize(10)} ${calcSize(20)} rgba(0,123,255,0.2)`,
    border: '1px solid rgba(255,255,255,0.1)',
    padding: '20px',
    '@media (max-width: 768px)': {
      width: '90%',
      minHeight: '80px',
      height: '80px',
      maxHeight: '80px',
      padding: '10px 20px',
    },
    '&:hover': {
      transform: 'translateY(-5px)',
      boxShadow: `0 ${calcSize(15)} ${calcSize(30)} rgba(0,123,255,0.3)`,
      backgroundColor: '#0056b3',
    },
  },
  mainButtonSmall: {
    width: '20%',
    maxWidth: calcSize(200),
    height: calcSize(50),
    minHeight: 'auto',
    boxShadow: `0 ${calcSize(4)} ${calcSize(8)} rgba(0,123,255,0.2)`,
    '@media (max-width: 768px)': {
      width: '45%',
    },
  },
  mainButtonText: {
    ...textStyles.primary,
    fontSize: calcFontSize(36),
    fontWeight: '600',
    transition: 'all 0.3s ease',
    whiteSpace: 'nowrap',
    '@media (max-width: 768px)': {
      fontSize: calcFontSize(18),
    },
  },
  mainButtonTextSmall: {
    fontSize: calcFontSize(16),
    textShadow: 'none',
  },
  glassCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.07)',
    borderRadius: calcSize(20),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    paddingVertical: calcSize(16),
    paddingHorizontal: calcSize(16),
    marginVertical: calcSize(8),
    marginHorizontal: 'auto',
    boxShadow: `0 ${calcSize(8)} ${calcSize(32)} rgba(0,0,0,0.1)`,
    backdropFilter: 'blur(8px)',
    width: '95%',
    maxWidth: calcSize(1600),
    alignSelf: 'center',
    overflow: 'auto',
  },
  cardTitle: {
    ...textStyles.primary,
    fontSize: calcFontSize(24),
    fontWeight: '700',
    marginBottom: 16,
    textAlign: 'center',
  },
  flexRowWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
    padding: 8,
  },
  subButton: {
    backgroundColor: 'rgba(108, 117, 125, 0.8)',
    padding: calcSize(12),
    borderRadius: calcSize(25),
    flex: 1,
    minWidth: calcSize(180),
    maxWidth: calcSize(300),
    height: calcSize(100),
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: `0 ${calcSize(4)} ${calcSize(8)} rgba(0,0,0,0.2)`,
    border: '1px solid rgba(255,255,255,0.1)',
    margin: calcSize(8),
    '@media (max-width: 768px)': {
      height: calcSize(80),
      padding: calcSize(8),
    },
  },
  subButtonText: {
    ...textStyles.primary,
    fontSize: calcFontSize(24),
    fontWeight: '500',
    whiteSpace: 'nowrap',
    '@media (max-width: 768px)': {
      fontSize: calcFontSize(18),
    },
  },
  formContainer: {
    padding: '16px',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
  },
  formRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    flexWrap: 'wrap',
    gap: '1vw',
  },
  formColumn: {
    flex: 1,
    minWidth: '250px',
    padding: '8px',
  },
  formGroup: {
    marginBottom: '1vh',
    width: '100%',
  },
  formLabel: {
    ...textStyles.primary,
    fontSize: calcFontSize(14),
    fontWeight: '500',
    marginBottom: 5,
    opacity: 0.9,
  },
  formInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: calcSize(8),
    padding: calcSize(8),
    height: calcSize(40),
    fontSize: calcFontSize(14),
    letterSpacing: 0.5,
    width: '100%',
  },
  formScrollContent: {
    paddingBottom: 20,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 5,
  },
  checkboxButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
    padding: 8,
    height: 36,
  },
  checkboxText: {
    ...textStyles.primary,
    fontSize: 14,
    marginLeft: 8,
    opacity: 0.9,
  },
  tableContainer: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'transparent',
    marginBottom: '16px',
    position: 'relative',
    zIndex: 1,
    borderRadius: '16px',
    
    /* Hem yatay hem dikey kaydırma açık */
    overflowX: 'hidden',
    overflowY: 'auto',

    /* .scrollable CSS'inden eklenen özellikler */
    boxSizing: 'border-box',
    padding: '20px',

    /* Scrollbar stilleri */
    '&::-webkit-scrollbar': {
      height: 6,
      marginBottom: 16,
    },
    '&::-webkit-scrollbar-track': {
      background: 'rgba(255, 255, 255, 0.1)',
      borderRadius: 4,
      margin: 16,
    },
    '&::-webkit-scrollbar-thumb': {
      background: 'rgba(255, 255, 255, 0.2)',
      borderRadius: 4,
      border: '2px solid #1a1f25',
      minWidth: 40,
    },
    '&::-webkit-scrollbar-button': {
      display: 'none',
    },
  },
  mainContainer: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    padding: '8px',
    paddingBottom: '0px',
    position: 'relative',
    zIndex: 1,
    transition: 'transform 0.3s ease',
    '@media (max-width: 768px)': {
      scrollSnapAlign: 'start',
      scrollSnapStop: 'always',
    },
  },
  headerContainer: {
    position: 'sticky',
    top: 0,
    zIndex: 10,
    backgroundColor: '#1a1f25',
    transition: 'transform 0.3s ease',
    transform: 'translateY(0)',
    '&.hidden': {
      transform: 'translateY(-100%)',
    },
  },
  tableHeader: {
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: 'rgba(0, 123, 255, 0.3)',
    position: 'sticky',
    top: 0,
    zIndex: 2,
    width: '100%',
    minWidth: 'fit-content',
    borderTopLeftRadius: '12px',
    borderTopRightRadius: '12px',
    overflow: 'visible',
    '& > div': {
      '&:hover': {
        backgroundColor: 'rgba(0, 123, 255, 0.4)',
      },
      '&:active': {
        backgroundColor: 'rgba(0, 123, 255, 0.5)',
      },
    },
  },
  headerCell: {
    minWidth: 150,
    maxWidth: 200,
    flex: 1,
    borderRightStyle: 'solid',
    borderRightWidth: 1,
    borderRightColor: 'rgba(255, 255, 255, 0.2)',
    padding: 8,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    position: 'relative',
    cursor: 'grab',
    userSelect: 'none',
    transition: 'all 0.2s ease',
    '&:lastChild': {
      borderRightStyle: 'none',
      borderRightWidth: 0,
    },
    '&:hover': {
      backgroundColor: 'rgba(0, 123, 255, 0.4)',
      cursor: 'grab',
    },
    '&:active': {
      cursor: 'grabbing',
      backgroundColor: 'rgba(0, 123, 255, 0.5)',
    },
    '&[draggable=true]': {
      cursor: 'grab',
      '&:hover': {
        backgroundColor: 'rgba(0, 123, 255, 0.4)',
        cursor: 'grab',
      },
      '&:active': {
        cursor: 'grabbing',
        backgroundColor: 'rgba(0, 123, 255, 0.5)',
      },
    },
  },
  tableHeaderCell: {
    ...textStyles.primary,
    fontWeight: '600',
    fontSize: calcFontSize(14),
    textAlign: 'center',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    width: '100%',
    pointerEvents: 'none',
    userSelect: 'none',
  },
  tableBody: {
    width: '100%',
    minWidth: 'fit-content',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'rgba(255, 255, 255, 0.07)',
    borderBottomLeftRadius: '12px',
    borderBottomRightRadius: '12px',
    overflow: 'hidden',
    position: 'relative',
    zIndex: 1,
  },
  tableRow: {
    display: 'flex',
    flexDirection: 'row',
    borderBottomStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    width: '100%',
    minWidth: 'fit-content',
    '&:lastChild': {
      borderBottomWidth: '0',
      borderBottomLeftRadius: '12px',
      borderBottomRightRadius: '12px',
    },
  },
  tableRowEven: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  tableRowOdd: {
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
  },
  tableCell: {
    minWidth: '150px',
    maxWidth: '200px',
    flex: 1,
    paddingTop: '8px',
    paddingBottom: '8px',
    paddingLeft: '8px',
    paddingRight: '8px',
    borderRightStyle: 'solid',
    borderRightWidth: '1px',
    borderRightColor: 'rgba(255, 255, 255, 0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    '&:lastChild': {
      borderRightStyle: 'none',
      borderRightWidth: '0',
    },
  },
  tableCellText: {
    ...textStyles.primary,
    fontSize: calcFontSize(14),
    textAlign: 'center',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    width: '100%',
    cursor: 'pointer',
  },
  noDataText: {
    ...textStyles.primary,
    textAlign: 'center',
    margin: 20,
    fontSize: calcFontSize(16),
    opacity: 0.7,
  },
  errorBorder: {
    borderColor: 'red',
    borderWidth: 1,
  },
  errorText: {
    color: '#ff4d4f',
    fontSize: calcFontSize(13),
    marginTop: 6,
    letterSpacing: 0.5,
    textShadow: '0 1px 2px rgba(255,77,79,0.2)',
  },
  formSubmitButton: {
    backgroundColor: '#007bff',
    padding: 10,
    borderRadius: 12,
    alignSelf: 'center',
    margin: 10,
  },
  formSubmitButtonText: {
    ...textStyles.primary,
    fontSize: calcFontSize(16),
    fontWeight: '600',
  },
  filterContainer: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    padding: 4,
    width: '100%',
    zIndex: 3,
  },
  filterInput: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 4,
    padding: 4,
    fontSize: calcFontSize(12),
    width: '100%',
    border: 'none',
    outlineWidth: 0,
  },
  filterSelect: {
    width: '100%',
    height: calcSize(32),
    padding: calcSize(4),
    fontSize: calcFontSize(12),
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    border: 'none',
    borderRadius: calcSize(4),
    color: '#000',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  filterSelectText: {
    fontSize: calcFontSize(12),
    color: '#000',
    textAlign: 'center',
  },
  paginationContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(26, 31, 37, 0.8)',
    borderRadius: 12,
    marginVertical: 8,
    marginHorizontal: 8,
    backdropFilter: 'blur(8px)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderStyle: 'solid',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.2)',
  },
  rowsPerPageContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  rowsPerPageSelect: {
    display: 'flex',
    flexDirection: 'row',
    gap: calcSize(8),
    padding: calcSize(8),
  },
  rowsPerPageOption: {
    padding: calcSize(6),
    borderRadius: calcSize(8),
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    height: calcSize(36),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: calcSize(45),
    border: '1px solid rgba(255, 255, 255, 0.1)',
    '&:hover': {
      backgroundColor: 'rgba(0, 123, 255, 0.2)',
      transform: 'translateY(-1px)',
      boxShadow: '0 2px 8px rgba(0, 123, 255, 0.2)',
    },
  },
  rowsPerPageOptionActive: {
    backgroundColor: 'rgba(0, 123, 255, 0.3)',
    border: '1px solid rgba(0, 123, 255, 0.5)',
    boxShadow: '0 2px 8px rgba(0, 123, 255, 0.2)',
  },
  rowsPerPageOptionText: {
    ...textStyles.primary,
    fontSize: calcFontSize(14),
    fontWeight: '500',
    textShadow: 'none',
  },
  rowsPerPageOptionTextActive: {
    fontWeight: '600',
    color: '#fff',
  },
  paginationControls: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: calcSize(12),
    marginLeft: calcSize(24),
  },
  paginationButton: {
    padding: calcSize(8),
    borderRadius: calcSize(8),
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    height: calcSize(36),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: calcSize(36),
    border: '1px solid rgba(255, 255, 255, 0.1)',
    '&:hover': {
      backgroundColor: 'rgba(0, 123, 255, 0.2)',
      transform: 'translateY(-1px)',
      boxShadow: '0 2px 8px rgba(0, 123, 255, 0.2)',
    },
  },
  paginationButtonDisabled: {
    opacity: 0.5,
    cursor: 'not-allowed',
    '&:hover': {
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      transform: 'none',
      boxShadow: 'none',
    },
  },
  paginationButtonText: {
    ...textStyles.primary,
    fontSize: calcFontSize(14),
    fontWeight: '600',
    textShadow: 'none',
  },
  paginationText: {
    ...textStyles.primary,
    fontSize: calcFontSize(14),
    fontWeight: '500',
    minWidth: 80,
    textAlign: 'center',
  },
  columnSelector: {
    position: 'relative',
    zIndex: 101,
  },
  columnSelectorButton: {
    backgroundColor: 'rgba(0, 123, 255, 0.3)',
    paddingVertical: calcSize(8),
    paddingHorizontal: calcSize(24),
    borderRadius: calcSize(8),
    height: calcSize(36),
    minWidth: calcSize(180),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    userSelect: 'none',
    '&:hover': {
      backgroundColor: 'rgba(0, 123, 255, 0.4)',
    },
  },
  columnSelectorButtonText: {
    color: '#fff',
    fontSize: calcFontSize(14),
    fontWeight: '500',
    letterSpacing: '0.5px',
  },
  columnSelectorDropdown: {
    position: 'absolute',
    top: '100%',
    left: '0',
    backgroundColor: 'rgba(26, 31, 37, 0.98)',
    borderRadius: calcSize(8),
    paddingTop: calcSize(12),
    paddingBottom: calcSize(12),
    paddingLeft: calcSize(12),
    paddingRight: calcSize(12),
    maxHeight: calcSize(400),
    overflowY: 'auto',
    boxShadow: `0 ${calcSize(8)} ${calcSize(24)} rgba(0,0,0,0.4)`,
    minWidth: calcSize(250),
    backdropFilter: 'blur(10px)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    display: 'flex',
    flexDirection: 'column',
    gap: calcSize(4),
    zIndex: 102,
    marginTop: calcSize(8),
  },
  columnSelectorItem: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    cursor: 'grab',
    paddingVertical: calcSize(8),
    paddingHorizontal: calcSize(12),
    backgroundColor: 'transparent',
    borderRadius: calcSize(6),
    transition: 'all 0.2s ease',
    userSelect: 'none',
    '&:hover': {
      backgroundColor: 'rgba(255,255,255,0.1)',
    },
    '&:active': {
      cursor: 'grabbing',
      backgroundColor: 'rgba(0, 123, 255, 0.2)',
    },
  },
  checkbox: {
    width: calcSize(18),
    height: calcSize(18),
    borderStyle: 'solid',
    borderWidth: calcSize(2),
    borderColor: 'rgba(255, 255, 255, 0.5)',
    borderRadius: calcSize(4),
    marginRight: calcSize(12),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s ease',
  },
  checkboxChecked: {
    backgroundColor: '#007bff',
    borderStyle: 'solid',
    borderWidth: '2px',
    borderColor: '#007bff',
    color: '#fff',
  },
  columnSelectorItemText: {
    color: '#fff',
    fontSize: calcFontSize(14),
    fontWeight: '500',
  },
  tableControls: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: calcSize(8),
    paddingTop: calcSize(8),
    paddingBottom: calcSize(8),
    paddingLeft: calcSize(12),
    paddingRight: calcSize(12),
    borderRadius: calcSize(12),
    backgroundColor: 'rgba(26, 31, 37, 0.5)',
    backdropFilter: 'blur(8px)',
    position: 'relative',
    zIndex: 100,
    gap: calcSize(16),
  },
  tableControlsRight: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: calcSize(16),
  },
  dropdownContainer: {
    position: 'absolute',
    zIndex: 2001,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    padding: 8,
    borderRadius: 8,
    marginTop: 4,
    maxHeight: 300,
    top: '100%',
    left: 0,
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
    overflowY: 'auto',
  },
  dropdownParent: {
    position: 'relative',
    zIndex: 2000,
  },
  filterDropdownContainer: {
    position: 'absolute',
    top: '100%',
    left: 0,
    backgroundColor: '#1a1f25',
    borderRadius: calcSize(8),
    paddingVertical: calcSize(8),
    paddingHorizontal: calcSize(8),
    minWidth: calcSize(150),
    boxShadow: `0 ${calcSize(4)} ${calcSize(12)} rgba(0,0,0,0.2)`,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    borderStyle: 'solid',
    zIndex: 5,
    marginTop: calcSize(4),
  },
  filterDropdownItem: {
    paddingVertical: calcSize(8),
    paddingHorizontal: calcSize(8),
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    '&:hover': {
      backgroundColor: 'rgba(255,255,255,0.1)',
    },
  },
  filterDropdownItemText: {
    color: '#fff',
    fontSize: calcFontSize(12),
  },
  filterDropdownItemActive: {
    backgroundColor: 'rgba(0,123,255,0.2)',
  },
  filterOperatorContainer: {
    position: 'relative',
    width: '100%',
    zIndex: 4,
  },
  filterOperatorButton: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    padding: calcSize(4),
    borderRadius: calcSize(4),
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  filterOperatorText: {
    color: '#fff',
    fontSize: calcFontSize(12),
  },
  '@-ms-viewport': {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    minimumScale: 1,
  },
  '@viewport': {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    minimumScale: 1,
  },
  touchAction: {
    pointerEvents: 'none',
  },
  dragIndicator: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: '4px',
    backgroundColor: '#007bff',
    opacity: 0,
    transition: 'opacity 0.2s ease',
  },
  dragIndicatorVisible: {
    opacity: 1,
  },
});

export default styles;
